# Manually configured in Vagrant provisioning -- will be overwritten by Puppet
# during configuration if local resolving is configured.
# Resolvers from the Vagrant subnet facts, except for SWH internal resolvers to
# avoid interactions between local testing and staging/prod.

forward-zone:
    name: '.'
    forward-addr: 128.93.77.234  # Inria's internal DNS
    forward-addr: 1.1.1.1        # Cloudflare – or replace by your own
